// List of all 47 Kenyan Counties
export const KENYAN_COUNTIES = [
  "Baringo",
  "Bomet",
  "Bungoma",
  "Busia",
  "Elgeyo-Marakwet",
  "Embu",
  "Garissa",
  "Homa Bay",
  "Isiolo",
  "Kajiado",
  "Kakamega",
  "Kericho",
  "Kiambu",
  "Kilifi",
  "Kirinyaga",
  "Kisii",
  "Kisumu",
  "Kitui",
  "Kwale",
  "Laikipia",
  "Lamu",
  "Machakos",
  "Makueni",
  "Mandera",
  "Marsabit",
  "Meru",
  "Migori",
  "Mombasa",
  "Murang'a",
  "Nairobi",
  "Nakuru",
  "Nandi",
  "Narok",
  "Nyamira",
  "Nyandarua",
  "Nyeri",
  "Samburu",
  "Siaya",
  "Taita-Taveta",
  "Tana River",
  "Tharaka-Nithi",
  "Trans Nzoia",
  "Turkana",
  "Uasin Gishu",
  "Vihiga",
  "Wajir",
  "West Pokot",
];

// Common TVET courses
export const TVET_COURSES = [
  "Automotive Engineering",
  "Building and Construction",
  "Business Management",
  "Carpentry and Joinery",
  "Computer Studies",
  "Electrical Engineering",
  "Electronics Engineering",
  "Fashion Design and Garment Making",
  "Food and Beverage",
  "Hair Dressing and Beauty Therapy",
  "Hospitality Management",
  "Information Communication Technology (ICT)",
  "Mechanical Engineering",
  "Plumbing",
  "Secretarial Studies",
  "Social Work and Community Development",
  "Welding and Fabrication",
];
